name: Deploy React APP to Azure by Terraform

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
  
jobs:
  react-terraform-azure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my github source code
      uses: actions/checkout@v2
     
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -var-file = "secrets.tfvars" -no-color 
        
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false 
